service: webhook-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: v1
  environment:
    WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_RECEIVER: ${env:EMAIL_RECEIVER}
    AUDIENCE_ID: ${env:AUDIENCE_ID}
    MAILCHIMP_SECRET: ${env:MAILCHIMP_SECRET}

functions:
  webhookHandler:
    handler: dist/handler.handler
    events:
      - http:
          path: webhook
          method: post

package:
  include:
    - dist/**
    - node_modules/**
    - .env
  exclude:
    - src/**
    - utils/**
    - .github/**
    - tsconfig.json
    - readme.md
    - test/**
    - README.md
    - .gitignore
    - serverless.yml